title: Mahmoud Mousa
email: your-email@example.com
description: >- 
  Cybersecurity Portfolio and Projects
url: "" # leave blank for GitHub Pages
github_username: your-github-username

theme: jekyll-theme-minimal
